### ISSUE TITLE
Request for adding support for Images : Very important

### ISSUE THREAD

**Issue by ksingh7** [protiumx/blogpub#11]
@protiumx first of all this is a great project, thanks a lot for developing this and open sourcing this. I have been researching about such automated tools and could not find one. You can easily make a decent business out of it my friend and i can bring you some customers :)

I have used your instructions and I am happy to report that they work flawlessly. 

To make this production-ready (i mean to be ready to use by the public), it currently lacks support to images
- Images on the cover page of a blog
- Images in the markdown body of the blog

I am not a TS/JS developer, otherwise, i could have sent you a PR. I can only request you to kindly prioritize adding the support for images and it would be ready to by the broader audience.

Other features that could be interesting are
- incremental updates to existing blogs
- adding support to hashnode would be awesome too
- adding support to publish only one blog 

I am happy to contribute in promoting / documentation / bragging about this tool if not with Code. Hope this helps.

**Comment by ksingh7** [comment]
Just for reference, I am using this as my MD file


```
---
title: Andys blog-1
description: My article description
tags: 'andy,atharv
cover_image: ./assets/cat.jpeg
---

## Serious title

This post goes on dev and medium both

![and some pictures too](./assets/cat.jpeg)
  
```

- The `cat.jpeg` file lives in the asset directory

![image](https://user-images.githubusercontent.com/9701902/152845623-a4f64312-d6e3-4a6b-8fa8-146734650db4.png)

- After publication, the image is broken

![image](https://user-images.githubusercontent.com/9701902/152845736-a724a2c5-1c7e-402a-b90f-8df59b524d09.png)

- For some unknown reason the image path is
``` https://[res.cloudinary.com](https://res.cloudinary.com/practicaldev/image/fetch/s--wZdqWAFP--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/v1/assets/cat.jpeg)/practicaldev/image/fetch/s--wZdqWAFP--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/v1/assets/cat.jpeg ```

- Ideally, the image path should be point to github inorder for this to work

``` https://github.com/ksingh7/rhd-blogs/blob/main/posts/assets/cat.jpeg ```

**Comment by ksingh7** [comment]
Hi @protiumx  Thanks for your positive response.

yes you are right , github is used to host images.

Medium support images at both start of the blog as well as the body of the blog. While Dev.to support images only in the body of the blog.

Currently, with your example, i am not able to add images to the body of the blog, because the image is not hosted on Github or any other publicly accessible path.

I will wait until you add support for image hosting via github.

**Comment by protiumx** [comment]
Hey @ksingh7 you should be able to use relative images with the v0.3.4 https://github.com/protiumx/blogpub/releases/tag/v0.3.4
Please refer to https://github.com/protiumx/blogpub-test/tree/main/blogs/blog-003 as example to use it.

Let me know if it works!

**Comment by protiumx** [comment]
@ksingh7 update to v0.4.1 so you can use relative paths for any media

**Comment by ksingh7** [comment]
@protiumx  Fantastic, i tried it just now and i am happy to report that it works like a charm

Thanks a lot for fixing this at the speed of light.

![image](https://user-images.githubusercontent.com/9701902/153276116-0dc8ad2a-2cee-4e45-b2c3-9330672942a4.png)

**Comment by protiumx** [comment]
@ksingh7 awesome! I'm closing this.
Please spread the word so I can get some help to add the rest of features mentioned on the TODO.
