### ISSUE TITLE
Medium does not respect Title provided in markdown

### ISSUE THREAD

**Issue by ksingh7** [protiumx/blogpub#16]
Hi @protiumx  This is a minor issue

When we publish the blog using Markdown on both dev.to and medium. 

The medium blog does not respect the `title` provided in the markdown. Below is my real blog post i published on medium using GHA

```
---
title: Increase timeout of OpenShift Web Terminal 
description: Learn how to increase the timeout of OpenShift Web Terminal from 15 minutes to any time you want.
tags: 'openshift,web,terminal'
cover_image: ./assets/cat.jpeg
canonical_url: null
published: true
---
```

![image](https://user-images.githubusercontent.com/9701902/153761027-f773f7a6-ddf3-4658-a9ba-09db815749d7.png)

- For comparison dev.to does respect the `title` provided in the markdown , very well
![image](https://user-images.githubusercontent.com/9701902/153761057-dbe528a8-80da-4ec8-b1ea-e83ddd45f197.png)

- Here is the markdown file i used to publish the blog on dev.to and medium
https://raw.githubusercontent.com/ksingh7/blogs/main/posts/increase-timeout-of-openshift-web-terminal.md

**Comment by protiumx** [comment]
Hi @ksingh7 
the `title` in the metadata is used only for the API payload, hence it doesn't get injected into the content of the article.
it would be better if you always add the title into the article like this
```md
# Increase timeout of OpenShift Web Terminal 
## Introduction
```
and avoid adding `title` to the metadata.

Also notice that `cover_image` and `canonical_url` are not supported by this action.
I could add support in the future. Feel free to open a feature request for that :)

**Comment by ksingh7** [comment]
Thanks @protiumx
